apiVersion: ENC[AES256_GCM,data:Tz0=,iv:zO1eSf24birniWArpRK8jrCevVmHxdIFGg+INkGkX5o=,tag:G41mLnaFcPI3KsWoHwSbCA==,type:str]
kind: ENC[AES256_GCM,data:kssY4gdT,iv:NBIQeGI5H3TqDu8aIuKxM4/dn5DKINl4CoELoS5mNsA=,tag:gWCtDRe+x5d+xWksWizoWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LDMTEBgy1gkCRgC6PcbQI+s4OxiwHEs=,iv:k+oTqtzlOevo7oZuJPps7ah07K5ydSqaA8J6cROIA9Q=,tag:xP39mhbzw10yPGc16orNfw==,type:str]
    namespace: ENC[AES256_GCM,data:EEHYJlR9PCFAJQ4=,iv:LrpME+PwYXzQbMlv/HAR6892FLvVNSjFzJGmyGHAOFo=,tag:CFIID4qAn7191ySRllJjnA==,type:str]
stringData:
    BACKSTAGE_GITHUB_TOKEN: ENC[AES256_GCM,data:uZQghGcP7c9VUctqquc1wKWqOqAmxkrWFFCBXCTtB3ZFdqrWhUqdUw==,iv:xYzRawS6Ge+ZG64jCxuTxzFWNjAXVdboP6Soz9X0gNw=,tag:SqkcKGpHUBparODyLdy6mg==,type:str]
    BACKSTAGE_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:E3H5LbKKpEfb/B8r4j/iBQFgbio=,iv:Vn2CR61VSDoieVHQLIP8YUsN3V0tsJ8vgPv/duvW6ls=,tag:FIB84CkwQiim9nOD3MNLyw==,type:str]
    BACKSTAGE_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:2mAv8u9GBkiILLg6LOn106vLnT6+WYAfgEdvW74QPYUh6Kv3Usi7vw==,iv:3AN1TC9RuzBmX3JDwL2Pi8c2tfZCyYxori2cGJQzK3A=,tag:4Lq/VXguba3OfgP2R2179Q==,type:str]
    BACKSTAGE_BACKEND_SECRET: ENC[AES256_GCM,data:Bxf2Z3D2uSLiz2qpIjbPXRCUip024L6WPaPQw+9KYjKjEF4j3ELsoktprYqO,iv:zY897Ag40PIXWmwDeVNtOo5cOLetpZRVP3DGXdYMrqQ=,tag:8xTNVDufu8a+QbF72ATSsA==,type:str]
    BACKSTAGE_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:koN857xakgtG,iv:4Bg5R1QvTggrEOR6HNbZvhd/wzsgj3sR5+9c0HHBNHw=,tag:Dq+pwUUPR/Vj/lkSftchJA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NFdrdHdLMUdoVkNIbEgr
            em1GMjA1SzZ0SWs3QVFyNEtBa3g3NXhvWkZZCm4xaXRXa3A4ZnZCbUE0M2tYZlZY
            MHp6QzMrMHNTeTFCTDJKTU0vRkIvRFkKLS0tIEkzRW01bTVlbXBnTVBWVkR2TlpL
            Rkl0K1lGY3NWQURqVDRIRmFEeHFPZ0UKxl/LIQJ4ZMkuPVWwal/GAOLuPHGRARSC
            iheJMaJSX0zGhK7JQJS1z2dpn2TF3GIPRdcZQXCMdKs9ZXXFtsdLTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T08:32:54Z"
    mac: ENC[AES256_GCM,data:AWeRrEy/2w+Ms8x72LzgXTIWkk7pRSu76qOXcY1Or/1ZKEtFudQHUcgNE9aJo7eV+hwaB82l4yfM6oSHYQXWa0X2+xiBvM3cWonSH8SKaw8wpseXrC0UDfcYJNjtIevB4YuSglc5reEhy8GngbNcd6LgxK3Zn5jcO1aPFFz50BY=,iv:++8Timsv7J+wPcESr0SC6bSvNMn841aVDp6IQblzY+s=,tag:zkSNKVjHfLv1fYE4uBDQaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
