apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: harvester-packer-devimage
  title: Update Harvester Packer Image (ubuntu25)
  description: Add packages and users to the ubuntu25 packer image and create a PR to trigger the build pipeline
  tags:
    - harvester
    - packer
    - infrastructure
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Additional Users
      properties:
        users:
          title: Additional Users
          type: array
          description: New users to add to the image (existing users are preserved)
          default: []
          items:
            type: object
            required: [name, ssh_key]
            properties:
              name:
                title: Username
                type: string
              groups:
                title: Groups
                type: string
                default: sudo
              shell:
                title: Shell
                type: string
                default: /bin/bash
              sudo:
                title: Sudo rule
                type: string
                default: "ALL=(ALL) NOPASSWD:ALL" # pragma: allowlist secret
              ssh_key:
                title: SSH Public Key
                type: string
                description: SSH public key for authorized access
          ui:options:
            addable: true
            orderable: false
            removable: true

    - title: Additional Packages
      properties:
        packages:
          title: Additional Packages
          type: array
          description: New packages to add to the image (existing packages are preserved)
          default: []
          items:
            type: string
          ui:options:
            addable: true
            orderable: false
            removable: true

  steps:
    - id: fetch-existing
      name: Fetch Existing Configuration
      action: fetch:plain
      input:
        url: https://github.com/stuttgart-things/platform-engineering-showcase/tree/main/harvester/packer/ubuntu25
        targetPath: existing

    - id: parse-existing-packages
      name: Parse Existing Packages
      action: utils:yaml:parse
      input:
        filePath: existing/packages.yaml

    - id: parse-existing-users
      name: Parse Existing Users
      action: utils:yaml:parse
      input:
        filePath: existing/users.yaml

    - id: fetch-base
      name: Render Configuration
      action: fetch:template
      input:
        url: ./skeleton
        values:
          existingPackages: ${{ steps['parse-existing-packages'].output.content.packages }}
          existingUsers: ${{ steps['parse-existing-users'].output.content.users }}
          newPackages: ${{ parameters.packages }}
          newUsers: ${{ parameters.users }}

    - id: create-pull-request
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=stuttgart-things&repo=platform-engineering-showcase
        branchName: backstage/update-ubuntu25-config
        update: true
        title: "Update ubuntu25 packer image config"
        description: |
          ## Packer Image Config Update (ubuntu25)

          Updated via Backstage software template.

          ### New Packages Added
          {%- for pkg in parameters.packages %}
          - `${{ pkg }}`
          {%- endfor %}
          {%- if not parameters.packages %}
          _None_
          {%- endif %}

          ### New Users Added
          {%- for user in parameters.users %}
          - `${{ user.name }}`
          {%- endfor %}
          {%- if not parameters.users %}
          _None_
          {%- endif %}
        targetPath: harvester/packer/ubuntu25

  output:
    links:
      - title: Pull Request
        icon: github
        url: ${{ steps['create-pull-request'].output.remoteUrl }}
    text:
      - title: Next Steps
        content: |
          PR created at ${{ steps['create-pull-request'].output.remoteUrl }}
          The packer build pipeline will trigger automatically.
          On success, the PR will be auto-merged.
