apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: harvester-packer-devimage
  title: Create Harvester VM-Template
  description: Add packages and users to the ubuntu packer image and create a PR to trigger the build pipeline
  tags:
    - harvester
    - packer
    - infrastructure
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Base Image
      properties:
        baseImage:
          title: Base Image
          type: string
          description: Select the base image for the packer build
          enum:
            - ubuntu
          default: ubuntu

    - title: Add New Users
      properties:
        users:
          title: Add New Users
          type: array
          description: New users to add to the image (existing users are preserved)
          default: []
          items:
            type: object
            required: [name, ssh_authorized_keys]
            properties:
              name:
                title: Username
                type: string
              groups:
                title: Groups
                type: string
                default: sudo
              shell:
                title: Shell
                type: string
                default: /bin/bash
              sudo:
                title: Sudo rule
                type: string
                default: "ALL=(ALL) NOPASSWD:ALL" # pragma: allowlist secret
              ssh_authorized_keys:
                title: SSH Public Keys
                type: array
                description: SSH public keys for authorized access
                items:
                  type: string
                minItems: 1
          ui:options:
            addable: true
            orderable: false
            removable: true

    - title: Additional Packages
      properties:
        packages:
          title: Additional Packages
          type: array
          description: New packages to add to the image (existing packages are preserved)
          default: []
          items:
            type: string
          ui:options:
            addable: true
            orderable: false
            removable: true

  steps:
    - id: fetch-existing-packages
      name: Fetch Existing Packages
      action: fetch:plain:file
      input:
        url: https://github.com/stuttgart-things/harvester/blob/main/packer/ubuntu/packages.yaml
        targetPath: ./packages.yaml

    - id: merge-packages
      name: Merge New Packages
      if: ${{ parameters.packages | length > 0 }}
      action: roadiehq:utils:merge
      input:
        path: ./packages.yaml
        mergeArrays: true
        content:
          packages: ${{ parameters.packages }}

    - id: fetch-existing-users
      name: Fetch Existing Users
      action: fetch:plain:file
      input:
        url: https://github.com/stuttgart-things/harvester/blob/main/packer/ubuntu/users.yaml
        targetPath: ./users.yaml

    - id: render-users-additions
      name: Render Users with Pragma Comments
      if: ${{ parameters.users | length > 0 }}
      action: fetch:template:file
      input:
        url: ./template/users-additions.yaml
        targetPath: ./users-additions.yaml
        values:
          users: ${{ parameters.users }}

    - id: parse-users-additions
      name: Parse Rendered Users
      if: ${{ parameters.users | length > 0 }}
      action: utils:yaml:parse
      input:
        filePath: ./users-additions.yaml

    - id: merge-users
      name: Merge New Users
      if: ${{ parameters.users | length > 0 }}
      action: roadiehq:utils:merge
      input:
        path: ./users.yaml
        mergeArrays: true
        content: ${{ steps['parse-users-additions'].output.content }}

    - id: render-catalog
      name: Render Catalog Info
      action: fetch:template:file
      input:
        url: ./template/catalog-info.yaml
        targetPath: ./catalog-info.yaml
        values:
          users: ${{ parameters.users }}
          packages: ${{ parameters.packages }}

    - id: create-pull-request
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=stuttgart-things&repo=harvester
        branchName: backstage/update-ubuntu-config
        update: true
        title: "Update ubuntu packer image config"
        description: |
          ## Packer Image Config Update (ubuntu)

          Updated via Backstage software template.

          ### Added Users
          ${{ (parameters.users | map(attribute='name') | join(', ')) or 'None' }}

          ### Added Packages
          ${{ (parameters.packages | join(', ')) or 'None' }}
        targetPath: packer/ubuntu

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/stuttgart-things/harvester/blob/main/packer/ubuntu/catalog-info.yaml
        optional: true

  output:
    links:
      - title: Pull Request
        icon: github
        url: ${{ steps['create-pull-request'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
    text:
      - title: Next Steps
        content: |
          PR created at ${{ steps['create-pull-request'].output.remoteUrl }}
          The packer build pipeline will trigger automatically.
          On success, the PR will be auto-merged.
      - title: Catalog Resource Preview
        content: | #pragma: allowlist secret
          ## Catalog Entity

          | Field | Value |
          |-------|-------|
          | **Name** | ubuntu25-packer-image |
          | **Kind** | Resource |
          | **Type** | packer-image |
          | **Lifecycle** | production |
          | **Owner** | platform-team |
          | **Base Image** | ${{ parameters.baseImage }} |

          ## Users

          ${{ 'No new users added.' if not parameters.users else '' }}
          {%- for user in parameters.users %}
          ### ${{ user.name }}

          | Setting | Value |
          |---------|-------|
          | **Groups** | ${{ user.groups or 'sudo' }} |
          | **Shell** | ${{ user.shell or '/bin/bash' }} |
          | **Sudo** | ${{ user.sudo or 'ALL=(ALL) NOPASSWD:ALL' }} | # pragma: allowlist secret
          | **SSH Keys** | ${{ user.ssh_authorized_keys | length }} key(s) |
          {%- for key in user.ssh_authorized_keys %}
          - `${{ key[:50] }}...`
          {%- endfor %}

          {%- endfor %}

          ## Packages

          ${{ 'No new packages added.' if not parameters.packages else '' }}
          {%- if parameters.packages %}
          | # | Package |
          |---|---------|
          {%- for pkg in parameters.packages %}
          | ${{ loop.index }} | `${{ pkg }}` |
          {%- endfor %}
          {%- endif %}
