apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: harvester-packer-devimage
  title: Update Harvester Packer Image (ubuntu25)
  description: Add packages and users to the ubuntu25 packer image and create a PR to trigger the build pipeline
  tags:
    - harvester
    - packer
    - infrastructure
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Additional Users
      properties:
        users:
          title: Additional Users
          type: array
          description: New users to add to the image (existing users are preserved)
          default: []
          items:
            type: object
            required: [name, ssh_authorized_keys]
            properties:
              name:
                title: Username
                type: string
              groups:
                title: Groups
                type: string
                default: sudo
              shell:
                title: Shell
                type: string
                default: /bin/bash
              sudo:
                title: Sudo rule
                type: string
                default: "ALL=(ALL) NOPASSWD:ALL" # pragma: allowlist secret
              ssh_authorized_keys:
                title: SSH Public Keys
                type: array
                description: SSH public keys for authorized access
                items:
                  type: string
                minItems: 1
          ui:options:
            addable: true
            orderable: false
            removable: true

    - title: Additional Packages
      properties:
        packages:
          title: Additional Packages
          type: array
          description: New packages to add to the image (existing packages are preserved)
          default: []
          items:
            type: string
          ui:options:
            addable: true
            orderable: false
            removable: true

  steps:
    - id: fetch-existing-packages
      name: Fetch Existing Packages
      action: fetch:plain:file
      input:
        url: https://github.com/stuttgart-things/platform-engineering-showcase/blob/main/harvester/packer/ubuntu25/packages.yaml
        targetPath: ./packages.yaml

    - id: merge-packages
      name: Merge New Packages
      action: roadiehq:utils:merge
      input:
        path: ./packages.yaml
        mergeArrays: true
        content:
          packages: ${{ parameters.packages }}

    - id: fetch-existing-users
      name: Fetch Existing Users
      action: fetch:plain:file
      input:
        url: https://github.com/stuttgart-things/platform-engineering-showcase/blob/main/harvester/packer/ubuntu25/users.yaml
        targetPath: ./users.yaml

    - id: merge-users
      name: Merge New Users
      action: roadiehq:utils:merge
      input:
        path: ./users.yaml
        mergeArrays: true
        content:
          users: ${{ parameters.users }}

    - id: render-catalog
      name: Render Catalog Info
      action: fetch:template:file
      input:
        url: ./template/catalog-info.yaml
        targetPath: ./catalog-info.yaml
        values: {}

    - id: create-pull-request
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=stuttgart-things&repo=platform-engineering-showcase
        branchName: backstage/update-ubuntu25-config
        update: true
        title: "Update ubuntu25 packer image config"
        description: |
          ## Packer Image Config Update (ubuntu25)

          Updated via Backstage software template.
        targetPath: harvester/packer/ubuntu25

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/stuttgart-things/platform-engineering-showcase/blob/main/harvester/packer/ubuntu25/catalog-info.yaml
        optional: true

  output:
    links:
      - title: Pull Request
        icon: github
        url: ${{ steps['create-pull-request'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
    text:
      - title: Next Steps
        content: |
          PR created at ${{ steps['create-pull-request'].output.remoteUrl }}
          The packer build pipeline will trigger automatically.
          On success, the PR will be auto-merged.
