apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: claim-to-merge-request
  title: Create Claim via Merge Request
  description: Render a Claim Machinery template and create a GitLab merge request
  tags:
    - claim-machinery
    - crossplane
    - gitlab
spec:
  owner: platform-team
  type: resource

  parameters:
    - title: Claim Configuration
      required:
        - claimTemplate
        - claimName
      properties:
        claimTemplate:
          title: Claim Template
          type: string
          description: Select a Claim Machinery template to render
          ui:field: ClaimMachineryPicker

        claimName:
          title: Claim Name
          type: string
          default: my-claim
          description: Name for your claim resource
          pattern: '^[a-z0-9-]+$'
          ui:help: 'Use lowercase letters, numbers, and hyphens only'

    - title: Template Parameters
      description: Configure the parameters for your selected template
      properties:
        parameters:
          title: Template Parameters
          type: object
          description: Parameters specific to the selected template
          ui:field: ClaimMachineryParameters

    - title: Repository Configuration
      description: Target repository for the claim manifest
      required:
        - targetPath
      properties:
        targetPath:
          title: Target Path in Repository
          type: string
          description: Path where the manifest will be stored (e.g., claims/production)
          default: claims
          ui:help: 'The directory path within resource-engines repository'

  steps:
    - id: render
      name: Render Claim Manifest
      action: claim-machinery:render
      input:
        template: ${{ parameters.claimTemplate }}
        parameters: ${{ parameters.parameters }}
        outputPath: ${{ parameters.targetPath }}

    - id: log-manifest
      name: Log Rendered Manifest
      action: debug:log
      input:
        message: |
          Claim rendered successfully!

          Template: ${{ parameters.claimTemplate }}
          File: ${{ steps['render'].output.filePath }}

          Manifest preview:
          ${{ steps['render'].output.manifest }}

    - id: create-merge-request
      name: Create GitLab Merge Request
      action: publish:gitlab:merge-request
      input:
        repoUrl: codehub.sva.de?owner=Lab/stuttgart-things/idp&repo=resource-engines
        branchName: claim-${{ parameters.claimTemplate }}-${{ parameters.claimName }}
        title: Add ${{ parameters.claimTemplate }} claim - ${{ parameters.claimName }}
        description: |
          ## Claim Manifest Created via Backstage

          **Template**: `${{ parameters.claimTemplate }}`
          **Claim Name**: `${{ parameters.claimName }}`
          **Target Path**: `${{ parameters.targetPath }}/${{ steps['render'].output.filePath }}`

          ### Manifest Details

          <details>
          <summary>Click to view manifest</summary>

          ```yaml
          ${{ steps['render'].output.manifest }}
          ```

          </details>

          ---

          Created automatically via Backstage Claim Machinery integration.
        targetPath: ${{ parameters.targetPath }}

    - id: log-summary
      name: Summary
      action: debug:log
      input:
        message: |
          Claim manifest rendered successfully!
          Merge request created: ${{ steps['create-merge-request'].output.mergeRequestUrl }}
          Branch: claim-${{ parameters.claimTemplate }}-${{ parameters.claimName }}

          Next steps:
          1. Review and merge the MR in GitLab
          2. Apply the manifest to your cluster

  output:
    links:
      - title: View Merge Request
        url: ${{ steps['create-merge-request'].output.mergeRequestUrl }}
        icon: gitlab
      - title: Repository
        url: https://codehub.sva.de/Lab/stuttgart-things/idp/resource-engines
        icon: gitlab
      - title: Rendered Manifest
        icon: description
        content: |
          ```yaml
          ${{ steps['render'].output.manifest }}
          ```
    text:
      - title: Merge Request Details
        content: |
          **Branch**: `claim-${{ parameters.claimTemplate }}-${{ parameters.claimName }}`
          **File Path**: `${{ parameters.targetPath }}/${{ steps['render'].output.filePath }}`

          [Open Merge Request](${{ steps['create-merge-request'].output.mergeRequestUrl }})
      - title: Next Steps
        content: |
          1. Review the merge request in GitLab
          2. Approve and merge the changes
          3. Apply to cluster: `kubectl apply -f ${{ parameters.targetPath }}/${{ steps['render'].output.filePath }}`
