---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.devName }}-packer-image
  description: ${{ values.devName }} self-service dev/playground Packer image, layered on golden ${{ values.goldenName }}
  annotations:
    github.com/project-slug: stuttgart-things/harvester
  tags:
    - harvester
    - packer
    - dev
    - playground
    - ${{ values.distroTag }}
{%- if values.users | length > 0 %}
    - users-customized
{%- endif %}
{%- if values.packages | length > 0 %}
    - packages-customized
{%- endif %}
spec:
  type: packer-image-dev
  lifecycle: experimental
  owner: platform-team
  dependsOn:
    - resource:default/${{ values.goldenName }}-packer-image
  profile:
    baseImage: ${{ values.profileBase }}
    goldenBase: ${{ values.goldenName }}
{%- if values.users | length > 0 %}
    addedUsers:
{%- for user in values.users %}
      - ${{ user.name }}
{%- endfor %}
{%- endif %}
{%- if values.packages | length > 0 %}
    addedPackages:
{%- for pkg in values.packages %}
      - ${{ pkg }}
{%- endfor %}
{%- endif %}
