---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ubuntu25-packer-image
  description: Ubuntu 25 Packer Image for Harvester
  annotations:
    github.com/project-slug: stuttgart-things/harvester
  tags:
    - harvester
    - packer
    - ubuntu
{%- if values.users | length > 0 %}
    - users-customized
{%- endif %}
{%- if values.packages | length > 0 %}
    - packages-customized
{%- endif %}
spec:
  type: packer-image
  lifecycle: production
  owner: platform-team
{%- if values.users | length > 0 or values.packages | length > 0 %}
  dependsOn: []
  profile:
{%- if values.users | length > 0 %}
    addedUsers:
{%- for user in values.users %}
      - ${{ user.name }}
{%- endfor %}
{%- endif %}
{%- if values.packages | length > 0 %}
    addedPackages:
{%- for pkg in values.packages %}
      - ${{ pkg }}
{%- endfor %}
{%- endif %}
{%- endif %}
