---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: claim-to-pull-request
  title: Render claim and Create Pull Request
  description: Create a GitHub Pull Request with a rendered claim manifest
spec:
  owner: platform-team
  type: test

  parameters:
    - title: Basic Info
      required:
        - claimTemplate
        - claimName
      properties:
        claimTemplate:
          title: Claim Template
          type: string
          ui:field: ClaimMachineryPicker
          ui:options:
            allowArbitraryValues: false

        claimName:
          title: Claim Name
          type: string
          default: test-claim
          pattern: '^[a-z0-9-]+$'

    - title: Template Parameters
      properties:
        parameters:
          title: Template Parameters
          type: object
          ui:field: ClaimMachineryParameters

    - title: GitHub Target
      required:
        - repoUrl
        - targetPath
      properties:
        repoUrl:
          title: Repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - stuttgart-things

        targetPath:
          title: Target Path in Repository
          type: string
          default: claims

  steps:
    - id: render
      name: Render Claim
      action: claim-machinery:render
      input:
        template: ${{ parameters.claimTemplate }}
        parameters: ${{ parameters.parameters }}
        outputPath: ${{ parameters.targetPath }}

    - id: create-pull-request
      name: Create GitHub Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: claim-${{ parameters.claimTemplate }}-${{ parameters.claimName }}
        title: Add ${{ parameters.claimTemplate }} claim - ${{ parameters.claimName }}
        description: |
          ## Claim Manifest Created via Backstage

          **Template**: ${{ parameters.claimTemplate }}
          **Claim Name**: ${{ parameters.claimName }}

          ```yaml
          ${{ steps['render'].output.manifest }}
          ```
        targetPath: ${{ parameters.targetPath }}

  output:
    links:
      - title: GitHub Pull Request
        icon: github
        url: ${{ steps['create-pull-request'].output.remoteUrl }}
